stream_over_http_enabled: true
server:
  http_listen_port: 3250
  log_level: info

query_frontend:
  search:
    max_duration: 1440h
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /var/lib/tempo/wal             # where to store the wal locally
    local:
      path: /var/lib/tempo/blocks

overrides:
  max_traces_per_user: 0
  ingestion_burst_size_bytes: 100000000
  ingestion_rate_limit_bytes: 50000000