{
 "title": "Clipboard API Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS", "label": "Default Prometheus instance", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Mutation Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clipboard API Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"clipboard_api_health\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total confirmed messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current messages in queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "ready messages" },
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "unacked messages"
    },
    {
     "expr": "rabbitmq_queue_messages_paged_out",
     "legendFormat": "paged out messages"
    }
   ]
  },
  {
   "title": "RabbitMQ Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"rabbitmq-server\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "GQL Mutations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(clipboard_api_graphql_mutation_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GQL Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(clipboard_api_graphql_query_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GQL Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(clipboard_api_graphql_subscription_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle DB Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "oracledb_up", "legendFormat": " " }
   ]
  },
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Client Time",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(client_system_time_unix_milliseconds[5m])",
     "legendFormat": "{{clipboard_id}}"
    },
    { "expr": "node_time_seconds * 1000", "legendFormat": "Reference Time" },
    { "expression": "$B - ($A / 1000)", "type": "math" }
   ]
  },
  {
   "title": "GraphQL Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "increase(clipboard_api_graphql_query_count[1m]) / 60",
     "legendFormat": "Query {{operationName}}"
    },
    {
     "expr": "increase(clipboard_api_graphql_mutation_count[1m]) / 60",
     "legendFormat": "Mutation {{operationName}}"
    },
    {
     "expr": "increase(clipboard_api_graphql_subscription_count[1m]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clipgraph API response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(clipboard_api_http_request_duration_seconds_sum{route=\"/clipgraph\", method=\"POST\"}[1m]) / rate(clipboard_api_http_request_duration_seconds_count{route=\"/clipgraph\", method=\"POST\"}[1m])",
     "legendFormat": "response time"
    },
    {
     "expr": "rate(clipboard_api_http_request_duration_seconds_count{route=\"/clipgraph\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(clipboard_api_http_requests_total{method=\"POST\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "clipboard_api_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle response time at Clipboard API",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(clipboard_api_oracle_query_time_summary_count[1m])",
     "legendFormat": "{{parentName}}"
    }
   ]
  },
  {
   "title": "ERP System DB wait times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "oracledb_wait_time_commit", "legendFormat": "Commit" },
    { "expr": "oracledb_wait_time_concurrency", "legendFormat": "Concurrency" },
    {
     "expr": "oracledb_wait_time_configuration",
     "legendFormat": "Configuration"
    },
    { "expr": "oracledb_wait_time_network", "legendFormat": "Network" },
    { "expr": "oracledb_wait_time_other", "legendFormat": "Other" },
    { "expr": "oracledb_wait_time_scheduler", "legendFormat": "Scheduler" },
    { "expr": "oracledb_wait_time_system_io", "legendFormat": "System I/O" },
    { "expr": "oracledb_wait_time_user_io", "legendFormat": "User I/O" }
   ]
  },
  {
   "title": "API Event Loop latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "clipboard_api_nodejs_eventloop_lag_min_seconds",
     "legendFormat": "min"
    },
    {
     "expr": "clipboard_apinodejs_eventloop_lag_mean_seconds",
     "legendFormat": "mean"
    },
    {
     "expr": "clipboard_api_nodejs_eventloop_lag_max_seconds",
     "legendFormat": "max"
    },
    {
     "expr": "clipboard_api_nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "99%"
    },
    {
     "expr": "clipboard_api_nodejs_eventloop_lag_seconds",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "ERP System DB Actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(oracledb_activity_execute_count[1m])",
     "legendFormat": "Execs"
    },
    {
     "expr": "rate(oracledb_activity_user_commits[1m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(oracledb_activity_user_rollbacks[1m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    { "expr": "loki_log_messages_total{}", "legendFormat": "{{level}}" }
   ]
  },
  {
   "title": "Log Storage (doesn't work)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "loki_chunk_store_stored_chunk_bytes_total",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}