{
 "title": "Oracledb",
 "description": "Oracle dashboard monitors db status, active sessions, user commits, wait times and more.",
 "tags": [ "oracle" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Widgets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "oracledb status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "calculatedInterval": "10m", "expr": "oracledb_up" }
   ]
  },
  {
   "title": "active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_active{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "user commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "execute count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "last scrape duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "total scrapes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "wait time concurrency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time commit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time system io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "wait time user io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "wait time application",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "wait time network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}\t"
    }
   ]
  }
 ]
}